version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expenses_tracker
    ports:
      - "3306:3306"
    networks:
      - expenses-net

  expenses-app:
    image: sohail28/expenses-tracker:latest
    container_name: expenses-app
    ports:
      - "9090:9090"
    depends_on:
      - mysql-db
    networks:
      - expenses-net

networks:
  expenses-net:
    driver: bridge
